services:
  - type: web
    env: node
    name: seedgame-bot
    buildCommand: |
      apt-get update -y
      apt-get install -y libgtk-4-1 libgraphene-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 libavif15 libenchant-2-2 libsecret-1-0 libmanette-0.2-0 libgles2-mesa libnss3 libx11-xcb1
      npm install
      npx playwright install --with-deps
    startCommand: node index.js
